_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 83
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.8.10
            "5": 0.18.3
            "6": 4.45.1
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
